Repository BlackPearlTech/SearchitTerminal, pull requests merged in 2019-07, with the labels that each got.

#62 Added Filters For Search Engines
  installer.sh
Labels: develop

#66 typo correction in README.txt file
  README.txt
Labels: maintain

#65 Added Facebook Search Filters
  installer.sh
Labels: develop

#67 Added reddit filters
  installer.sh
Labels: develop

#68 added linkedin filters
  installer.sh
Labels: develop

#71 Google+ Removed
  installer.sh
Labels: bug, develop

#73 Search Filters For Pinterest
  installer.sh
Labels: develop

#74 Added quora search filters. this fixes #56
  installer.sh
Labels: develop

#75 Github Filters
  installer.sh
Labels: develop

#80 added gitlab search filters
  installer.sh
Labels: develop

#81 added stackoverflow search filters
  installer.sh
Labels: develop

#82 added help section for wikipedia
  installer.sh
Labels: develop

#83 added help section for tumblr
  installer.sh
Labels: develop

#84 added search filters for duckit. this fixes #78
  installer.sh
Labels: develop

#85 added search filters for googleit. this fixes #79
  installer.sh
Labels: develop

#86 Amazon Search Filters Added.
  installer.sh
Labels: develop

#87 git corupt
  installer.sh
Labels: bug

#88 Ebay Search Filters
  installer.sh
Labels: develop

#92 Updated Relase-Note. This Fixes #91
  Release-Note
Labels: maintain

#93 Updated README.txt and CONTRIBUTING.md.
  CONTRIBUTING.md
  README.txt
Labels: maintain

#94 Updated README.md.
  README.md
Labels: maintain

#97 Update issue Fixed
  installer.sh
Labels: bug

#99 Data Update.
  installer.sh
Labels: maintain

#103 Updated Release Note For v2.0.5
  Release-Note
  Version
  installer.sh
Labels: maintain

#104 Modified Update Functionality.
  installer.sh
Labels: invalid

#105 Update For v2.1.5
  README.md
  README.txt
  Release-Note
  Version
  installer.sh
Labels: maintain

#108 Module Design
  coreModules/about.dat
  coreModules/browserSelect.dat
  coreModules/config.dat
  coreModules/defaultBrowserCheck.dat
  coreModules/defaultSearch.dat
  coreModules/defaultSearchEngineCheck.dat
  coreModules/duckit.dat
  coreModules/globalVariable.dat
  coreModules/googleit.dat
  coreModules/help.dat
  coreModules/init.dat
  coreModules/intro.dat
  coreModules/parameterCheck.dat
  coreModules/searchengineSelect.dat
  coreModules/uninstall.dat
  coreModules/uninstallCheck.dat
  coreModules/update.dat
  installer.sh
  searchModules/searchEngines/baidu.dat
  searchModules/searchEngines/bing.dat
  searchModules/searchEngines/duckduckgo.dat
  searchModules/searchEngines/google.dat
  searchModules/searchEngines/searx.dat
  searchModules/searchEngines/shodan.dat
  searchModules/searchEngines/startpage.dat
  searchModules/searchEngines/yahoo.dat
  searchModules/searchEngines/yandex.dat
  searchModules/searchSites/amazon.dat
  searchModules/searchSites/ebay.dat
  searchModules/searchSites/facebook.dat
  searchModules/searchSites/github.dat
  searchModules/searchSites/gitlab.dat
  searchModules/searchSites/linkedin.dat
  searchModules/searchSites/pinterest.dat
  searchModules/searchSites/quora.dat
  searchModules/searchSites/reddit.dat
  searchModules/searchSites/stackoverflow.dat
  searchModules/searchSites/tumblr.dat
  searchModules/searchSites/twitter.dat
  searchModules/searchSites/wikipedia.dat
  searchModules/searchSites/youtube.dat
Labels: develop

#109 updated for v2.2.5
  README.md
  README.txt
  Release-Note
  installer.sh
Labels: maintain
